# -*- coding: utf-8 -*-
"""WEEK6_Engin11_Lab_JupyterNotebook vF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uXNuxKEudeJrG-mJEagPUOc_tnZUxQpZ
"""

#Plot indoor tables

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

indoor = pd.read_csv('lab5_trial5.csv')
indoor = indoor.iloc[15:].reset_index(drop=True) #drop first 15 rows because the trials are 2 seconds apart -- we cut the first 30 seconds we were not yet outside

# Convert time to seconds since start
indoor["time_seconds"] = indoor["time"] - indoor["time"].iloc[0]

# Plot every variable vs time
variables = [c for c in indoor.columns if c not in ["time", "time_seconds"]]

for var in variables:
    plt.figure()
    plt.plot(indoor["time_seconds"], indoor[var])
    plt.xlabel("Time (seconds)")
    plt.ylabel(var)
    plt.title(f"{var} vs Time")
    plt.show()

#Plot outdoor variables
outdoor = pd.read_csv('lab5_trial6.csv')
outdoor = outdoor.iloc[15:].reset_index(drop=True) #cut first 30 seconds
# Convert time to seconds since start
outdoor["time_seconds"] = outdoor["time"] - outdoor["time"].iloc[0]

# Plot every variable vs time
variables = [c for c in outdoor.columns if c not in ["time", "time_seconds"]]

for var in variables:
    plt.figure()
    plt.plot(outdoor["time_seconds"], outdoor[var])
    plt.xlabel("Time (seconds)")
    plt.ylabel(var)
    plt.title(f"{var} vs Time")
    plt.show()

# Plot each variable with indoor and outdoor on same graph
for var in variables:
    plt.figure()
    plt.plot(indoor["time_seconds"], indoor[var], label="Indoor")
    plt.plot(outdoor["time_seconds"], outdoor[var], label="Outdoor")
    plt.xlabel("Time (seconds)")
    plt.ylabel(var)
    plt.title(f"{var}: Indoor vs Outdoor")
    plt.legend()
    plt.show()

# Create histogram for each variable
for var in variables:
    plt.figure()

    plt.hist(indoor[var], bins=30, alpha=0.5, label="Indoor")
    plt.hist(outdoor[var], bins=30, alpha=0.5, label="Outdoor")

    plt.xlabel(var)
    plt.ylabel("Frequency")
    plt.title(f"{var}: Indoor vs Outdoor Distribution")
    plt.legend()
    plt.show()

#The weather data seems to be a lot more meaningful given that the particulate matter is more random and susceptible to small changes. The temperature data covered a lot larger of a spread for the Outdoor measurements, which if you look at the time series makes sense because as the sensor calibrated to outdoor temperature it steadily decreased. The Gas distribution follows a similar pattern, but the outdoor measurements were increimentally higher than the indoor measurements. Humidity was a lot higher outside which also makes sense given it rained earlier today. Air pressure corresponded to this higher humidity by being lower outside, also most likely attributed to the inclement weather. Finally, the altitude increased for the 'outdoor' measurements because a flight of stairs was taken to bring the sensor outdoors.

import pandas as pd

trial5 = pd.read_csv('lab5_trial5.csv')
trial6 = pd.read_csv('lab5_trial6.csv')


t5_mean_temp = trial5['temp'].mean()
t5_std_temp = trial5['temp'].std()
t6_mean_temp = trial6['temp'].mean()
t6_std_temp = trial6['temp'].std()


t5_mean_pressure = trial5['pressure'].mean()
t5_std_pressure = trial5['pressure'].std()
t6_mean_pressure = trial6['pressure'].mean()
t6_std_pressure = trial6['pressure'].std()


t5_mean_humidity = trial5['humidity'].mean()
t5_std_humidity = trial5['humidity'].std()
t6_mean_humidity = trial6['humidity'].mean()
t6_std_humidity = trial6['humidity'].std()


t5_mean_altitude = trial5['altitude'].mean()
t5_std_altitude = trial5['altitude'].std()
t6_mean_altitude = trial6['altitude'].mean()
t6_std_altitude = trial6['altitude'].std()


t5_mean_gas = trial5['gas'].mean()
t5_std_gas = trial5['gas'].std()
t6_mean_gas = trial6['gas'].mean()
t6_std_gas = trial6['gas'].std()


t5_mean_pm10_std = trial5['pm10 standard'].mean()
t5_std_pm10_std = trial5['pm10 standard'].std()
t6_mean_pm10_std = trial6['pm10 standard'].mean()
t6_std_pm10_std = trial6['pm10 standard'].std()

t5_mean_pm25_std = trial5['pm25 standard'].mean()
t5_std_pm25_std = trial5['pm25 standard'].std()
t6_mean_pm25_std = trial6['pm25 standard'].mean()
t6_std_pm25_std = trial6['pm25 standard'].std()

t5_mean_pm100_std = trial5['pm100 standard'].mean()
t5_std_pm100_std = trial5['pm100 standard'].std()
t6_mean_pm100_std = trial6['pm100 standard'].mean()
t6_std_pm100_std = trial6['pm100 standard'].std()


t5_mean_pm10_env = trial5['pm10 env'].mean()
t5_std_pm10_env = trial5['pm10 env'].std()
t6_mean_pm10_env = trial6['pm10 env'].mean()
t6_std_pm10_env = trial6['pm10 env'].std()

t5_mean_pm25_env = trial5['pm25 env'].mean()
t5_std_pm25_env = trial5['pm25 env'].std()
t6_mean_pm25_env = trial6['pm25 env'].mean()
t6_std_pm25_env = trial6['pm25 env'].std()

t5_mean_pm100_env = trial5['pm100 env'].mean()
t5_std_pm100_env = trial5['pm100 env'].std()
t6_mean_pm100_env = trial6['pm100 env'].mean()
t6_std_pm100_env = trial6['pm100 env'].std()


t5_mean_03um = trial5['03um'].mean()
t5_std_03um = trial5['03um'].std()
t6_mean_03um = trial6['03um'].mean()
t6_std_03um = trial6['03um'].std()

t5_mean_05um = trial5['05um'].mean()
t5_std_05um = trial5['05um'].std()
t6_mean_05um = trial6['05um'].mean()
t6_std_05um = trial6['05um'].std()

t5_mean_10um = trial5['10um'].mean()
t5_std_10um = trial5['10um'].std()
t6_mean_10um = trial6['10um'].mean()
t6_std_10um = trial6['10um'].std()

t5_mean_25um = trial5['25um'].mean()
t5_std_25um = trial5['25um'].std()
t6_mean_25um = trial6['25um'].mean()
t6_std_25um = trial6['25um'].std()

t5_mean_50um = trial5['50um'].mean()
t5_std_50um = trial5['50um'].std()
t6_mean_50um = trial6['50um'].mean()
t6_std_50um = trial6['50um'].std()

t5_mean_100um = trial5['100um'].mean()
t5_std_100um = trial5['100um'].std()
t6_mean_100um = trial6['100um'].mean()
t6_std_100um = trial6['100um'].std()


#significance


cols = [
    'temp', 'pressure', 'humidity', 'altitude', 'gas',
    'pm10 standard', 'pm25 standard', 'pm100 standard',
    'pm10 env', 'pm25 env', 'pm100 env',
    '03um', '05um', '10um', '25um', '50um', '100um'
]

print("STATISTICAL SIGNIFICANCE CHECK ")

for col in cols:

    m5 = trial5[col].mean()
    sd5 = trial5[col].std()


    m6 = trial6[col].mean()
    sd6 = trial6[col].std()


    diff = abs(m6 - m5)
    diff_sigma = diff/sd5
    print("Separated by:", diff_sigma, "standard deviations")

    threshold = 3 * sd5

    print(f"Variable: {col.upper()}")
    print(f"Trial 5 Mean: {m5:.4f}, Std Dev: {sd5:.4f}")
    print(f"Trial 6 Mean: {m6:.4f}, Std Dev: {sd6:.4f}")


    if diff > threshold:
        print("RESULT: They are statistically different")
    else:
        print("RESULT: They are NOT statistically different")
    print("-" * 30)



"""Our data does somewhat resemble a Gaussian, as the histogram is highest in the middle, however, it does not fully converfe to the normal distribution.

Especially since we cut out the first 30 seconds for outdoor, we do not have an extremeley large amount of data, only about 100-150 data points. If we had more data points, it would be more likely to more closely resemble the Gaussian.
"""



#Plot indoor tables

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

indoor_other = pd.read_csv('test.csv')
indoor_other = indoor_other.iloc[15:].reset_index(drop=True) #drop first 15 rows because the trials are 2 seconds apart -- we cut the first 30 seconds we were not yet outside

# Convert time to seconds since start
indoor_other["time_seconds"] = indoor_other["time"] - indoor_other["time"].iloc[0]

# Plot every variable vs time
variables = [c for c in indoor_other.columns if c not in ["time", "time_seconds"]]

for var in variables:
    plt.figure()
    plt.plot(indoor_other["time_seconds"], indoor_other[var])
    plt.xlabel("Time (seconds)")
    plt.ylabel(var)
    plt.title(f"{var} vs Time")
    plt.show()

#Plot outdoor variables
outdoor_other = pd.read_csv('outside.csv')
outdoor_other = outdoor_other.iloc[15:].reset_index(drop=True) #cut first 30 seconds
# Convert time to seconds since start
outdoor_other["time_seconds"] = outdoor_other["time"] - outdoor_other["time"].iloc[0]

# Plot every variable vs time


#The weather data seems to be a lot more meaningful given that the particulate matter is more random and susceptible to small changes. The temperature data covered a lot larger of a spread for the Outdoor measurements, which if you look at the time series makes sense because as the sensor calibrated to outdoor temperature it steadily decreased. The Gas distribution follows a similar pattern, but the outdoor measurements were increimentally higher than the indoor measurements. Humidity was a lot higher outside which also makes sense given it rained earlier today. Air pressure corresponded to this higher humidity by being lower outside, also most likely attributed to the inclement weather. Finally, the altitude increased for the 'outdoor' measurements because a flight of stairs was taken to bring the sensor outdoors.

import pandas as pd

indoor_new = pd.read_csv('test.csv')
outdoor_new = pd.read_csv('outside.csv')

# Mappings from original column names (in trial5/trial6) to new column names (in indoor_new/outdoor_new)
column_map = {
    'temp': "['Temperature']",
    'pressure': "['Pressure']",
    'humidity': "['Relative Humidity']",
    'altitude': "['Altitude']",
    'gas': "['Gas']",
    '03um': 'particles03',
    '05um': 'particles05',
    '10um': 'particles10',
    '25um': 'particles25',
    '50um': 'particles50',
    '100um': 'particles100'
}

# The 'cols' list should be the original column names from trial5/trial6
cols_original = list(column_map.keys())

print("STATISTICAL SIGNIFICANCE CHECK ")

for col_original in cols_original:
    col_new = column_map[col_original]

    # For trial5 and trial6 (original dataframes)
    m5 = trial5[col_original].mean()
    sd5 = trial5[col_original].std()

    m6 = trial6[col_original].mean()
    sd6 = trial6[col_original].std()

    # For indoor_new and outdoor_new (new dataframes)
    m_in = indoor_new[col_new].mean()
    sd_in = indoor_new[col_new].std()

    m_out = outdoor_new[col_new].mean()
    sd_out = outdoor_new[col_new].std()

    # Compare indoor_new to trial5
    diff_in_vs_t5 = abs(m_in - m5)
    diff_sigma_in_vs_t5 = diff_in_vs_t5 / sd_in if sd_in != 0 else float('inf') # Handle division by zero

    threshold_in_vs_t5 = 3 * sd_in

    print(f"Indoor Variable: {col_new.upper()} (vs. {col_original.upper()})")
    print("Separated by:", diff_sigma_in_vs_t5, "standard deviations")
    print(f"Original (trial5) Mean: {m5:.4f}, Std Dev: {sd5:.4f}")
    print(f"New (indoor_new) Mean: {m_in:.4f}, Std Dev: {sd_in:.4f}")

    if diff_in_vs_t5 > threshold_in_vs_t5:
        print("RESULT: They are statistically different")
    else:
        print("RESULT: They are NOT statistically different")
    print("-" * 30)

    # Compare outdoor_new to trial6
    diff_out_vs_t6 = abs(m_out - m6)
    diff_sigma_out_vs_t6 = diff_out_vs_t6 / sd_out if sd_out != 0 else float('inf') # Handle division by zero

    threshold_out_vs_t6 = 3 * sd_out

    print(f"Outdoor Variable: {col_new.upper()} (vs. {col_original.upper()})")
    print("Separated by:", diff_sigma_out_vs_t6, "standard deviations")
    print(f"Original (trial6) Mean: {m6:.4f}, Std Dev: {sd6:.4f}")
    print(f"New (outdoor_new) Mean: {m_out:.4f}, Std Dev: {sd_out:.4f}")


    if diff_out_vs_t6 > threshold_out_vs_t6:
        print("RESULT: They are statistically different")
    else:
        print("RESULT: They are NOT statistically different")
    print("-" * 30)

#Plot indoor tables

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

new_outdoor = pd.read_csv('lab5_trial12.csv')
new_outdoor = new_outdoor.iloc[15:].reset_index(drop=True) #drop first 15 rows because the trials are 2 seconds apart -- we cut the first 30 seconds we were not yet outside

# Convert time to seconds since start
new_outdoor["time_seconds"] = new_outdoor["time"] - new_outdoor["time"].iloc[0]


trial12 = pd.read_csv('lab5_trial12.csv')
trial6 = pd.read_csv('lab5_trial6.csv')

t12_mean_temp = trial12['temp'].mean()
t12_std_temp = trial12['temp'].std()
t6_mean_temp = trial6['temp'].mean()
t6_std_temp = trial6['temp'].std()


t12_mean_pressure = trial12['pressure'].mean()
t12_std_pressure = trial12['pressure'].std()
t6_mean_pressure = trial6['pressure'].mean()
t6_std_pressure = trial6['pressure'].std()


t12_mean_humidity = trial12['humidity'].mean()
t12_std_humidity = trial12['humidity'].std()
t6_mean_humidity = trial6['humidity'].mean()
t6_std_humidity = trial6['humidity'].std()


t12_mean_altitude = trial12['altitude'].mean()
t12_std_altitude = trial12['altitude'].std()
t6_mean_altitude = trial6['altitude'].mean()
t6_std_altitude = trial6['altitude'].std()


t12_mean_gas = trial12['gas'].mean()
t_std_gas = trial12['gas'].std()
t6_mean_gas = trial6['gas'].mean()
t6_std_gas = trial6['gas'].std()


t12_mean_pm10_std = trial12['pm10 standard'].mean()
t12_std_pm10_std = trial12['pm10 standard'].std()
t6_mean_pm10_std = trial6['pm10 standard'].mean()
t6_std_pm10_std = trial6['pm10 standard'].std()

t12_mean_pm25_std = trial12['pm25 standard'].mean()
t12_std_pm25_std = trial12['pm25 standard'].std()
t6_mean_pm25_std = trial6['pm25 standard'].mean()
t6_std_pm25_std = trial6['pm25 standard'].std()

t12_mean_pm100_std = trial12['pm100 standard'].mean()
t12_std_pm100_std = trial12['pm100 standard'].std()
t6_mean_pm100_std = trial6['pm100 standard'].mean()
t6_std_pm100_std = trial6['pm100 standard'].std()


t12_mean_pm10_env = trial12['pm10 env'].mean()
t12_std_pm10_env = trial12['pm10 env'].std()
t6_mean_pm10_env = trial6['pm10 env'].mean()
t6_std_pm10_env = trial6['pm10 env'].std()

t12_mean_pm25_env = trial12['pm25 env'].mean()
t12_std_pm25_env = trial12['pm25 env'].std()
t6_mean_pm25_env = trial6['pm25 env'].mean()
t6_std_pm25_env = trial6['pm25 env'].std()

t12_mean_pm100_env = trial12['pm100 env'].mean()
t12_std_pm100_env = trial12['pm100 env'].std()
t6_mean_pm100_env = trial6['pm100 env'].mean()
t6_std_pm100_env = trial6['pm100 env'].std()


t12_mean_03um = trial12['03um'].mean()
t12_std_03um = trial12['03um'].std()
t6_mean_03um = trial6['03um'].mean()
t6_std_03um = trial6['03um'].std()

t12_mean_05um = trial12['05um'].mean()
t12_std_05um = trial12['05um'].std()
t6_mean_05um = trial6['05um'].mean()
t6_std_05um = trial6['05um'].std()

t12_mean_10um = trial12['10um'].mean()
t12_std_10um = trial12['10um'].std()
t6_mean_10um = trial6['10um'].mean()
t6_std_10um = trial6['10um'].std()

t12_mean_25um = trial12['25um'].mean()
t12_std_25um = trial12['25um'].std()
t6_mean_25um = trial6['25um'].mean()
t6_std_25um = trial6['25um'].std()

t12_mean_50um = trial12['50um'].mean()
t12_std_50um = trial12['50um'].std()
t6_mean_50um = trial6['50um'].mean()
t6_std_50um = trial6['50um'].std()

t12_mean_100um = trial12['100um'].mean()
t12_std_100um = trial12['100um'].std()
t6_mean_100um = trial6['100um'].mean()
t6_std_100um = trial6['100um'].std()


cols = [
    'temp', 'pressure', 'humidity', 'altitude', 'gas',
    'pm10 standard', 'pm25 standard', 'pm100 standard',
    'pm10 env', 'pm25 env', 'pm100 env',
    '03um', '05um', '10um', '25um', '50um', '100um'
]

print("STATISTICAL SIGNIFICANCE CHECK ")

for col in cols:

    m12 = trial12[col].mean()
    sd12 = trial12[col].std()


    m6 = trial6[col].mean()
    sd6 = trial6[col].std()


    diff = abs(m6 - m12)
    diff_sigma = diff/sd12
    print("Separated by:", diff_sigma, "standard deviations")

    threshold = 3 * sd12

    print(f"Variable: {col.upper()}")
    print(f"New Outdoor Mean: {m12:.4f}, Std Dev: {sd12:.4f}")
    print(f"Past Outdoor Mean: {m6:.4f}, Std Dev: {sd6:.4f}")


    if diff > threshold:
        print("RESULT: They are statistically different")
    else:
        print("RESULT: They are NOT statistically different")
    print("-" * 30)

import numpy as np
from scipy import stats

# Data
x = new_outdoor["temp"]
y = new_outdoor['humidity']

# Linear regression
slope, intercept, r_value, p_value, std_err = stats.linregress(x, y)
r_squared = r_value**2
x_line = np.linspace(x.min(), x.max(), 100)
y_line = slope * x_line + intercept

plt.figure()
plt.scatter(new_outdoor["temp"], new_outdoor['humidity'], label="New Outdoor Data")
plt.plot(x_line, y_line, color='red', label=f"Best Fit (R²={r_squared:.4f})")
plt.xlabel("Temperature")
plt.ylabel('Humidity')
plt.title(f"Temp vs Humidity")
plt.legend()
plt.show()

"""The hidden variable is time, because the data may be different when measured at earlier/later or even at different times of the day."""

# Data
z = new_outdoor['pressure']

# Linear regression
slope, intercept, r_value, p_value, std_err = stats.linregress(x, z)
r_squared = r_value**2
x_line = np.linspace(x.min(), x.max(), 100)
y_line = slope * x_line + intercept

plt.figure()
plt.scatter(new_outdoor["temp"], new_outdoor['pressure'], label="New Outdoor Data")
plt.plot(x_line, y_line, color='red', label=f"Best Fit (R²={r_squared:.4f})")
plt.xlabel("Temperature")
plt.ylabel('Pressure')
plt.title(f"Temp vs Pressure")
plt.legend()
plt.show()





"""Temperature and humidity show a strong linear correlation with an R^2 value > 0.9.

Temperature and pressure also show a linear correlation but it is less strong with a R^2 of 0.63. We expect this relationship because of PV=nRT.
"""

# Data
a = new_outdoor['25um']

# Linear regression
slope, intercept, r_value, p_value, std_err = stats.linregress(x, a)
r_squared = r_value**2
x_line = np.linspace(x.min(), x.max(), 100)
y_line = slope * x_line + intercept

plt.figure()
plt.scatter(new_outdoor["temp"], new_outdoor['25um'], label="New Outdoor Data")
plt.plot(x_line, y_line, color='red', label=f"Best Fit (R²={r_squared:.4f})")
plt.xlabel("Temperature")
plt.ylabel('PM 2.5')
plt.title(f"Temp vs Pm2.5")
plt.legend()
plt.show()

"""The data matches because we did the same delay every time."""