# -*- coding: utf-8 -*-
"""week_11_lab_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xPTOgrph5QWczbmrLuZP-1V44GqpJzP9
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

# 3.1

noAl = pd.read_csv('week_11_data/noAl', header = None)
sheet1 = pd.read_csv('week_11_data/1sheet', header = None)
sheet2 = pd.read_csv('week_11_data/2sheet', header = None)
sheet3 = pd.read_csv('week_11_data/3sheet', header = None)
tung1 = pd.read_csv('week_11_data/1tungsten', header = None)
tung2 = pd.read_csv('week_11_data/2tungsten', header = None)
tung3 = pd.read_csv('week_11_data/3tungsten', header = None)

# Column 0 is the timestamp
noAl_counts = noAl.drop(columns=0).sum(axis=1)
sheet1_counts = sheet1.drop(columns=0).sum(axis=1)
sheet2_counts = sheet2.drop(columns=0).sum(axis=1)
sheet3_counts = sheet3.drop(columns=0).sum(axis=1)
tung1_counts = tung1.drop(columns=0).sum(axis=1)
tung2_counts = tung2.drop(columns=0).sum(axis=1)
tung3_counts = tung3.drop(columns=0).sum(axis=1)


# 3.2

plt.figure()
plt.hist(noAl_counts,   bins=15, alpha=0.5, label='no Al')
plt.hist(sheet1_counts, bins=15, alpha=0.5, label='1 sheet')
plt.hist(sheet2_counts, bins=15, alpha=0.5, label='2 sheets')
plt.hist(sheet3_counts, bins=15, alpha=0.5, label='3 sheets')
plt.xlabel('Counts per interval')
plt.ylabel('Frequency')
plt.title('Counts per interval for each Al measurement')
plt.legend()
plt.show()

print('noAl:   mean =', round(noAl_counts.mean(), 2),   '  std =', round(noAl_counts.std(), 2),   '  sqrt(mean) =', round(np.sqrt(noAl_counts.mean()), 2))
print('1sheet: mean =', round(sheet1_counts.mean(), 2), '  std =', round(sheet1_counts.std(), 2), '  sqrt(mean) =', round(np.sqrt(sheet1_counts.mean()), 2))
print('2sheet: mean =', round(sheet2_counts.mean(), 2), '  std =', round(sheet2_counts.std(), 2), '  sqrt(mean) =', round(np.sqrt(sheet2_counts.mean()), 2))
print('3sheet: mean =', round(sheet3_counts.mean(), 2), '  std =', round(sheet3_counts.std(), 2), '  sqrt(mean) =', round(np.sqrt(sheet3_counts.mean()), 2))

"""2.a) The measured standard deviations are close the square roots of the means. This is what we expect because decay counts follow Poisson distributions.  
b) The recorded counts decrease as thickness increases, which we
expect because thicker materials in between absorbs more of the radiation before it can reach the detector.
"""

# 3.3

# Uncertainty = sqrt(total counts)
noAl_total = noAl_counts.sum()
sheet1_total = sheet1_counts.sum()
sheet2_total = sheet2_counts.sum()
sheet3_total = sheet3_counts.sum()
tung1_total = tung1_counts.sum()
tung2_total = tung2_counts.sum()
tung3_total = tung3_counts.sum()

noAl_err = np.sqrt(noAl_total)
sheet1_err = np.sqrt(sheet1_total)
sheet2_err = np.sqrt(sheet2_total)
sheet3_err = np.sqrt(sheet3_total)
tung1_err = np.sqrt(tung1_total)
tung2_err = np.sqrt(tung2_total)
tung3_err = np.sqrt(tung3_total)

#Assume each sheet is 2 cm thick
al_thicknesses = [2, 4, 6]
al_counts      = [sheet1_total, sheet2_total, sheet3_total]
al_errors      = [sheet1_err, sheet2_err, sheet3_err]

w_thicknesses  = [2, 4, 6]
w_counts       = [tung1_total, tung2_total, tung3_total]
w_errors       = [tung1_err, tung2_err, tung3_err]

plt.figure()
plt.errorbar(al_thicknesses, al_counts, yerr=al_errors, fmt='o-', capsize=5, label='Aluminum')
plt.errorbar(w_thicknesses,  w_counts,  yerr=w_errors,  fmt='s-', capsize=5, label='Tungsten')
plt.yscale('log')
plt.xlabel('Absorber thickness')
plt.ylabel('Total counts')
plt.title('Total counts vs absorber thickness')
plt.legend()
plt.show()

#3.4

al_slope, al_intercept, al_r, al_p, al_se = stats.linregress(al_thicknesses, np.log(al_counts))
w_slope,  w_intercept,  w_r,  w_p,  w_se  = stats.linregress(w_thicknesses,  np.log(w_counts))

al_mu = -al_slope
w_mu  = -w_slope

print('Aluminum absorption coefficient: mu =', round(al_mu, 3), 'cm^-1')
print('Tungsten absorption coefficient:  mu =', round(w_mu, 3),  'cm^-1')

al_fit_x = np.linspace(2, 6, 100)
al_fit_y = np.exp(al_intercept + al_slope * al_fit_x)

w_fit_x = np.linspace(2, 6, 100)
w_fit_y = np.exp(w_intercept + w_slope * w_fit_x)

noAl_total = noAl_counts.sum()
noAl_err   = np.sqrt(noAl_total)
plt.figure()
plt.errorbar(0, noAl_total, yerr=noAl_err, fmt='D', color='gray', capsize=5, label='no absorber')
plt.errorbar(al_thicknesses, al_counts, yerr=al_errors, fmt='o', color='royalblue', capsize=5, label='Al data')
plt.errorbar(w_thicknesses,  w_counts,  yerr=w_errors,  fmt='s', color='firebrick',  capsize=5, label='W data')
plt.plot(al_fit_x, al_fit_y, '--', color='royalblue', label='Al fit')
plt.plot(w_fit_x,  w_fit_y,  '--', color='firebrick',  label='W fit')
plt.yscale('log')
plt.xlabel('Absorber thickness (cm)')
plt.ylabel('Total counts')
plt.title('Attenuation fits')
plt.legend()
plt.show()

"""Aluminum absorption coefficient: mu = 0.008 cm^-1  
Tungsten absorption coefficient:  mu = 0.039 cm^-1

We did not have time to try a second source, but we would not expect the absorption coefficients to be exactly the same. Higher energy sources would be harder to absorb, and vice verse for lower energy sources, so you would expect different absorption coefficients.
"""

